# Generated by Django 4.2.6 on 2025-09-23 18:17

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='token',
            field=models.CharField(default=projects.models.generate_invite_token, max_length=64, unique=True),
        ),
    ]
