"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------------
# Environment
# ----------------------------------------------------------------------------
env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(str, 'insecure-default'),
    ALLOWED_HOSTS=(list, []),
    DATABASE_URL=(str, f"sqlite:///{(Path(__file__).resolve().parent.parent / 'db.sqlite3').as_posix()}"),
    TIME_ZONE=(str, 'America/Sao_Paulo'),
    LANGUAGE_CODE=(str, 'en-us'),
    CORS_ALLOW_ALL_ORIGINS=(bool, True),
    STATIC_URL=(str, 'static/'),
    MEDIA_URL=(str, '/media/'),
    # Environment
    ENVIRONMENT=(str, 'development'),
    # Storage
    AWS_STORAGE_BUCKET_NAME=(str, ''),
    AWS_S3_REGION_NAME=(str, ''),
    AWS_S3_ENDPOINT_URL=(str, ''),
    AWS_ACCESS_KEY_ID=(str, ''),
    AWS_SECRET_ACCESS_KEY=(str, ''),
    # Supabase
    SUPABASE_PROJECT_URL=(str, ''),
    SUPABASE_ANON_KEY=(str, ''),
    # Email
    EMAIL_BACKEND=(str, 'django.core.mail.backends.console.EmailBackend'),
    EMAIL_HOST=(str, ''),
    EMAIL_PORT=(int, 587),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_USE_TLS=(bool, True),
    # Cache
    CACHE_URL=(str, ''),
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')
# Normalize and safe defaults for local dev
if isinstance(ALLOWED_HOSTS, str):
    try:
        import json as _json
        parsed = _json.loads(ALLOWED_HOSTS)
        ALLOWED_HOSTS = parsed if isinstance(parsed, list) else [str(parsed)]
    except Exception:
        ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS.split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # Allow all in dev to avoid DisallowedHost, or specify common localhost hosts
    ALLOWED_HOSTS = ['*']

# Ensure common dev hosts are allowed
COMMON_DEV_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'host.docker.internal', 'web']
if ALLOWED_HOSTS != ['*']:
    existing = set(ALLOWED_HOSTS)
    for h in COMMON_DEV_HOSTS:
        if h not in existing:
            ALLOWED_HOSTS.append(h)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # external packages
    'rest_framework',
    'django_filters',
    'corsheaders',
    # Mirach apps
    'accounts',
    'projects',
    'datasets',
    'predictions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'project_extras': 'projects.templatetags.project_extras',
            },
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_TIME_LIMIT = env.int('CELERY_TASK_TIME_LIMIT', default=60 * 30)
CELERY_TASK_SOFT_TIME_LIMIT = env.int('CELERY_TASK_SOFT_TIME_LIMIT', default=60 * 25)
CELERY_TASK_ROUTES = {
    'predictions.tasks.run_prediction_task': {
        'queue': 'predictions_high' if env.bool('PREDICTIONS_HIGH_PRIORITY', default=False) else 'predictions_default'
    }
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': env.db(),  # parses DATABASE_URL
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE')

TIME_ZONE = env('TIME_ZONE')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = env('STATIC_URL')
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = env('MEDIA_URL')
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------------------------------
# Storage (MinIO/S3/Supabase via django-storages)
# ----------------------------------------------------------------------------
ENVIRONMENT = env('ENVIRONMENT').lower()
SUPABASE_PROJECT_URL = env('SUPABASE_PROJECT_URL')
SUPABASE_ANON_KEY = env('SUPABASE_ANON_KEY')

# Check if Supabase is configured
USE_SUPABASE = bool(SUPABASE_PROJECT_URL and SUPABASE_ANON_KEY)

if ENVIRONMENT == 'development':
    # Use MinIO for development
    INSTALLED_APPS = [*INSTALLED_APPS, 'storages']
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME') or 'us-east-1'
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL') or 'http://localhost:9000'
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID') or 'minioadmin'
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY') or 'minioadmin'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
elif ENVIRONMENT == 'production' and USE_SUPABASE:
    # Use Supabase Storage for production
    INSTALLED_APPS = [*INSTALLED_APPS, 'storages']
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = 'us-east-1'  # Supabase default region
    AWS_S3_ENDPOINT_URL = f"{SUPABASE_PROJECT_URL}/storage/v1/s3"
    AWS_ACCESS_KEY_ID = SUPABASE_ANON_KEY
    AWS_SECRET_ACCESS_KEY = SUPABASE_ANON_KEY
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_CUSTOM_DOMAIN = f"{SUPABASE_PROJECT_URL}/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
elif ENVIRONMENT == 'production' and not USE_SUPABASE:
    # Use traditional S3 for production (if Supabase not configured)
    INSTALLED_APPS = [*INSTALLED_APPS, 'storages']
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME') or None
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL') or None
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = env('CORS_ALLOW_ALL_ORIGINS')

# Email
EMAIL_BACKEND = env('EMAIL_BACKEND')
if EMAIL_BACKEND != 'django.core.mail.backends.console.EmailBackend':
    EMAIL_HOST = env('EMAIL_HOST')
    EMAIL_PORT = env('EMAIL_PORT')
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = env('EMAIL_USE_TLS')

# Cache
if env('CACHE_URL'):
    CACHES = {
        'default': env.cache('CACHE_URL')
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mirach-local-cache'
        }
    }

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'accounts.auth.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': env('DRF_USER_RATE', default='1000/day'),
        'anon': env('DRF_ANON_RATE', default='100/day'),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
